### ISSUE TITLE
Create realmd executable

### ISSUE THREAD

**Issue by WillAyd** [gtker/wow_messages#68]
Love the library - lots of great work. Would you have any interest in creating an executable for realmd? I see the crate for wow_messages but as far as I can tell its just a library. 

Looking to learn Rust so happy to contribute this if interested

**Comment by gtker** [comment]
Depending on exactly what you want with this it might already exist.

* [The `wow_login_messages`](https://github.com/gtker/wow_messages/tree/main/wow_login_messages) crate has message definitions for the "realmd" auth protocol.
* [The various examples](https://github.com/gtker/wow_messages/blob/f97a6c66be3eb2bcc197c36af2473fffabab4101/examples/vanilla_server/src/auth.rs#L26) implement the authentication protocol in order to get the client into the server.
* [The `dev_wow_auth_server` binary](https://github.com/gtker/dev_wow_auth_server) that I wrote which is intended for people writing in other languages to be able to bypass writing an auth server.
* [My general purpose server that I use to further develop `wow_messages` and test out APIs](https://github.com/gtker/wow_vanilla_server) implements the auth protocol in order to have clients connect.

The [`awesome-wow-rust`](https://github.com/arlyon/awesome-wow-rust) repo has a Discord link as well as some project links if you want to find something to contribute to. For `wow_messages` I don't think there's really that much you're able to contribute other than improving the `.wowm` descriptions. I think [`wrath-rs`](https://github.com/Victov/wrath-rs) is the most popular and feature rich Rust emulator currently and I think there's plenty of things to do. You could also ask on [the Discord](https://discord.gg/RjSytaEuuX).

**Comment by WillAyd** [comment]
Awesome thanks for all of the resources - I'll look through these
