### ISSUE TITLE
Character select screen missing "AddOns" button when connecting to vanilla-server example

### ISSUE THREAD

**Issue by bigglesss** [gtker/wow_messages#8]
Client version: 1.12.1

Compared Wireshark packets to a standard vanilla private server and there doesn't seem to be any difference between the auth packets, but the client interface refuses to show the `CharacterSelectAddonsButton`. The client code calls `GetNumAddOns`, but I'm not sure where this is pulling data from, and it's not sending any packets (using `wow` filter in Wireshark) other than the standard RealmList/auth procedure stuff.

The addons are loaded (roughly) correctly on loading into the world, so the issue is definitely something to do with the server response. Perhaps you need to load in correctly into the world and receive some kind of World message in order to initialise addons correctly on a new server?

https://gtker.com/wow_messages/docs/smsg_addon_info.html only seems to supported in 3.3.5, so I don't think that's the problem.

EDIT: It looks like the WOWW display filter in Wireshark doesn't work out of the box, so I imagine there's some packet I'm missing that might explain this.

Very nice project, I was looking for a rust lib to handle WoW SRP when I was playing around with Vmangos auth and stumbled across it!

**Comment by Victov** [comment]
>https://gtker.com/wow_messages/docs/smsg_addon_info.html only seems to supported in 3.3.5, so I don't think that's the problem.

It's very likely that the Addons button doesn't show up because the simple example server does that absolute minimum to go from login to character selection to in-world. It's likely that the vanilla client is waiting for SMSG_ADDON_INFO, but the minimal example does not send it.

I'm working on a Wrath server based on this package and added SMSG_ADDON_INFO for 3.3.5. That's why it exists. That it doesn't exist for vanilla does not mean that the vanilla game does not need that message, more likely that nobody has gotten to it yet, or there was some complicated feature required in the parser to make it work and @gtker hasn't added support for that in the parser.

**Comment by BigSchnozz1** [comment]
Makes sense, I didn't realise that my WOWW filter in Wireshark wasn't working properly, so assumed all the packets in the Character Selection interface were Login Packets.

**Comment by gtker** [comment]
Thanks for the interest! If you intend on using the library for your own server let me know, I'm very certain that I have made mistakes whether that be in the library APIs or message transcribtions.

The problem is that I haven't added SMSG_ADDON_INFO for 1.12 to the wowm, so it's not being generated for the docs or library. When you run the `wow_message_parser` it actually spits out which (vanilla) messages are missing, and why:
```text
	SMSG_COMPRESSED_UPDATE_OBJECT: Compressed
	SMSG_SEND_MAIL_RESULT: Nested if
	SMSG_AUCTION_COMMAND_RESULT: Nested if
	SMSG_WARDEN_DATA: Encryption
	CMSG_WARDEN_DATA: Encryption
	SMSG_ADDON_INFO: Compressed
	SMSG_COMPRESSED_MOVES: Compressed
```
I get that this isn't the most user friendly approach, but in my defense I didn't actually think anybody cared about this until @Victov wanted to use it for his Wrath server.

The examples are really just the most minimal setup required to log into the world in order to provide something that works, but is as simple as possible.

The [Ember project](https://github.com/EmberEmu/Ember) has [an implementation](https://github.com/EmberEmu/Ember/blob/90b9a7b43df4744f856e81e3efcf1de92bcb4ebf/src/libs/protocol/include/protocol/server/AddonInfo.h#L74), although I don't know if they have the `Addon`s button show up. You could always ask about it in the discord, https://github.com/Chaosvex is very knowledgeable about the client and especially the more obscure early-connection things.

I realize that having a (mostly) complete message reference can be annoying when there are known deficiencies. I'll add working on the compressed objects to my TODO for when I get the time. :)


> Very nice project, I was looking for a rust lib to handle WoW SRP when I was playing around with Vmangos auth and stumbled across it!

I also have a [crate for reading Vanilla DBC files](https://github.com/gtker/wow_vanilla_dbc) if you need it.

> EDIT: It looks like the WOWW display filter in Wireshark doesn't work out of the box, so I imagine there's some packet I'm missing that might explain this.

Coincidentally I also wrote the WOWW wireshark dissector. Depending on which version you have you might be missing some of the newer features I added. I compile Wireshark from source and use that for development and on the current master I just filter for `woww` (or `wow || woww` if I want both auth and world) and it doesn't seem to leave out any messages.

**Comment by BigSchnozz1** [comment]
>Thanks for the interest! If you intend on using the library for your own server let me know, I'm very certain that I have made mistakes whether that be in the library APIs or message transcribtions.

Right now I'm mostly just noodling around the codebase, having a play around, using it as a platform for trying to polish up my Rust knowledge. I'm not sure if you're intending to eventually branch this out into a hobby Vanilla server (I'd assume so, or I guess you could just really into writing network layers), but if you do I'll absolutely be following along and hopefully contributing.

>The problem is that I haven't added SMSG_ADDON_INFO for 1.12 to the wowm, so it's not being generated for the docs or library. When you run the wow_message_parser it actually spits out which (vanilla) messages are missing, and why:

That's super handy, I'm not super familiar with Rust yet so I'm still grappling with the codebase. I saw that there's a `compressed` tag on the `compressed_addon_info` field, which I'm guessing is intended to eventually be used in the WOWM Rust compilation (/ rust_printer) stage to decompress the data automatically?

I had a look at @Victov's wrath implementation of the decompression and it doesn't seem too tricky, so may try and figure that out as a mini-bug.

>Coincidentally I also wrote the WOWW wireshark dissector. Depending on which version you have you might be missing some of the newer features I added. I compile Wireshark from source and use that for development and on the current master I just filter for woww (or wow || woww if I want both auth and world) and it doesn't seem to leave out any messages.

Yeah, I found that out after googling around for a bit, I think I was using an older version (default Ubuntu). Building it from the git source seems to have fixed it, really useful stuff!

**Comment by gtker** [comment]
> I'm not sure if you're intending to eventually branch this out into a hobby Vanilla server

I have one locally, but it's very WIP and is mostly used as a test bed for this repo. 

>  (I'd assume so, or I guess you could just really into writing network layers), but if you do I'll absolutely be following along and hopefully contributing.

I'm not actually sure, right now the fun is actually more in creating libraries and information that other people can use rather than quickly getting a working server.


> That's super handy, I'm not super familiar with Rust yet so I'm still grappling with the codebase. I saw that there's a compressed tag on the compressed_addon_info field, which I'm guessing is intended to eventually be used in the WOWM Rust compilation (/ rust_printer) stage to decompress the data automatically?

That was the intention, but I'm not actually sure exactly how I want to do it. If you want to investigate it and figure somthing out you're more than welcome. Just keep in mind that the `wow_message_parser` is in a really rough state since it was exclusively used by myself and I know the limitations of the format, so error messages might be confusing (or just some random assert!/unwrap).

I have added the unimplemented vanilla messages to both the library and the documentation, in order to avoid giving people the impression that they don't exist for 1.12. The library just takes a `Vec<u8>` in the message, but all the size and header stuff is handled for you, so it might be easier to prototype through that.

**Comment by Victov** [comment]
Keep in mind that it's not actually the SMSG_ADDON_INFO message that has compression inside of it. There is a block of compressed data inside CMSG_AUTH_SESSION that contains information about the users addon, and the server parses that and sends SMSG_ADDON_INFO back, but that has just some regular data. I have that workflow working [here](https://github.com/Victov/wrath-rs/blob/6237fa95c1715f1594a92b8b16cd13afe35bd7ab/world_server/src/handlers/login_handler.rs#L70) 

Keep in mind that I'm in the middle of a refactor on that branch to start using this crate, so it's a mess, but the linked file is completed and can be used as a reference for what exactly is going on with that compressed block and the intended response. Also keep in mind that this is all WotLK and might be different for vanilla/TBC

**Comment by gtker** [comment]
@bigglesss The [current master](https://github.com/gtker/wow_messages/commit/ab70ecec90e5f56e93826f048be7b1f69ef48aaf) has what I believe to be a correct `SMSG_ADDON_INFO`.

I primarily took it from [Ember](https://github.com/EmberEmu/Ember/blob/05583fe4acfc1db897f0d8ec0c1ceea34b313319/src/libs/protocol/include/protocol/server/AddonInfo.h) with some peeking at vmangos.

Only caveat is that the `KeyVersion` is for now just a regular enum since it needs to be in an if statement. I have considered implementing it using the `self.value` feature as

```rust
enum KeyVersion : u8 {
	ZERO = 0;
	OTHER = self.value;
}
```

which would translate to Rust as 
```rust
enum KeyVersion {
	Zero,
	Other(u8),
}
```
but this doesn't entirely work with how I currently do if statements so please let me know if the message is correct.

**Comment by bigglesss** [comment]
Have tested this out with a local impl of the SMSG_ADDON_INFO in the example server and it works great! I'll either commit that code or see if I can get the addon_info field in CMSG_AUTH_SESSION to decompress into structs instead of a Vec<u8> first, and then write a cleaner snipper for the example server

GJ
