### ISSUE TITLE
3.3.5a SMSG_UPDATE_OBJECT minimum required fields to spawn player

### ISSUE THREAD

**Issue by Kangaroux** [gtker/wow_messages#94]
The required fields listed on the [wowdev wiki](https://wowdev.wiki/SMSG_UPDATE_OBJECT) for vanilla don't apply to wotlk. Including an example payload for 3.3.5a on the [SMSG_UPDATE_OBJECT page](https://gtker.com/wow_messages/docs/smsg_update_object.html) would be helpful, as well as calling out the fields which are required.

I've included a sample payload here which is the minimum required data to get past the loading screen. This spawns a female human warrior in Goldshire. [Credit to this 2016 post from ownedcore](https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-emulator-servers/wow-emu-questions-requests/390468-smsg_update_object-documentation.html). For some reason the payload from the post includes every update mask field, though only 3 `uint32` masks are used.

Raw hex (header is unencrypted for this example but should be encrypted when sent to the client)
```
006fa9000100000003010804210000000000000000000000cdd70bc6357e04c3f90fa74200000000000000000000803f00008c420000904000000000000000000000000000000000d00f4940000000000303000000000080001800000008000000000000000b0000000c4d00000c4d0000
```

```go
// header
00 6f            // size (111)
a9 00            // opcode (169)
01 00 00 00      // number of objects

// start of object
03               // CREATE_OBJECT2 (trinity uses this for creating new objects
                 // and CREATE_OBJECT for existing objects? not sure)
01 08            // packed guid (id: 8)
04               // player object type

// movement block
21 00            // update flag self | update flag living
00 00 00 00      // movement flags
00 00            // movement flags cont.
00 00 00 00      // timestamp (trinity uses unix epoch, caching related?)
cd d7 0b c6      // x pos (-8949.95)
35 7e 04 c3      // y pos (-132.493)
f9 0f a7 42      // z pos (83.5312)
00 00 00 00      // orientation
00 00 00 00      // fall time
00 00 80 3f      // walk speed (1.0f)
00 00 8c 42      // run speed (70.0f)
00 00 90 40      // reverse speed (4.5f)
00 00 00 00      // swim speed (0.0f)
00 00 00 00      // swim reverse speed (0.0f)
00 00 00 00      // flight speed (0.0f)
00 00 00 00      // flight reverse speed (0.0f)
d0 0f 49 40      // turn speed (3.14159)
00 00 00 00      // pitch rate (0.0f)

// update/values block
03                // size of mask (measured in uint32, 3*4 = 12 byte mask)

// mask
03 00 00 00       // OBJECT_GUID (size=2)
00 00 80 00       // UNIT_FACTIONTEMPLATE
18 00 00 00       // UNIT_DISPLAYID | UNIT_NATIVEDISPLAYID

// OBJECT_GUID
08 00 00 00       // low guid (id: 8)
00 00 00 00       // high guid (2 MSB = 0x0000 for player, haven't tested this much)

// not including any of these seems to cause a segfault
01 00 00 00       // UNIT_FACTIONTEMPLATE (race, 0x1 = human)
0c 4d 00 00       // UNIT_DISPLAYID (0x4D0C = human female)
0c 4d 00 00       // UNIT_NATIVEDISPLAYID (same as above)
```

Some misc. notes:
- `OBJECT_SCALE_X` is needed for the character model to appear, otherwise the scale is zero and your camera is first person
- The client doesn't seem to mind if you omit `OBJECT_TYPE` when spawning the player. It made no difference for me
- Omitting `UNIT_BYTES_0` caused the talent screen to be blank and probably would lead to some other funny interactions
- Omitting `UNIT_HEALTH` causes your player to spawn in as a corpse
- Omitting `UNIT_MAXHEALTH` seems to be a bit undefined, it didn't show unit health in the UI and probably would cause a crash if I took damage
- Omitting `UNIT_LEVEL` causes your player level to be zero when you open the character panel (C)

**Comment by gtker** [comment]
Thanks for the contribution, I've added your example as a `wowm` `test` [here](https://github.com/gtker/wow_messages/blob/4a542f717ebda91b15e23591ce225c1f45942418/wow_message_parser/wowm/world/gameobject/smsg_update_object_3_3_5.wowm#L206). This will show the example in the docs as well as help validate generated library code.

I had to add the `OBJECT_TYPE` since the Rust library doesn't handle `UpdateMask`s without an `OBJECT_TYPE`, something I'll have to fix at some point.

Since it seems you're working [on your own server](https://github.com/Kangaroux/gomaggus) I would suggest looking into auto generating the message definitions. The [`intermediate_representation.json`](https://github.com/gtker/wow_messages/blob/main/intermediate_representation.json) file in the repo contains all the messages in a computer readable format to make this easier. The [`intermediate_representation_schema.json`](https://github.com/gtker/wow_messages/blob/main/intermediate_representation_schema.json) is a [JSON Typedef schema](https://jsontypedef.com/) that allows you to create [data types for many programming languages](https://github.com/jsontypedef/json-typedef-codegen) that makes it easier. I created [a library for Python](https://github.com/gtker/wow_messages_python/) by writing a generator in Python as a proof of concept. I'm currently working on a C# version as well in order to more thoroughly test out the IR and make improvements, although it's not on Github yet.

I realize that the documentation is rather poor and I'm working on updating it as well as making a few changes, so feel free to ask if you have any questions.

I would recommended joining the [awesome-rust discord](https://github.com/arlyon/awesome-wow-rust). I'm not sure if there's a Golang equivalent, but you can also ask general emulation questions there. There are a lot of details that can't be logically deduced or are very difficult to reverse engineer, so it'll save you tons of time if you can just ask someone.

**Comment by gtker** [comment]
Fixed with the adding of the test and addition to the wiki.
